/* ============================================================
 * 四级英语修行阁 —— 单词库 + 艾宾浩斯记忆引擎
 * 素材说明：以下为 CET-4 高频词汇样例（word/释义/例句），
 * 结构对齐牛津等权威词典字段，便于后续替换为正版授权素材。
 * ============================================================ */
(function (global) {
  'use strict';

  // 每批学习新词数量
  const NEW_WORDS_PER_BATCH = 8;

  /* 艾宾浩斯遗忘曲线复习周期（天）：当日、1、2、4、7、15、30 */
  const REVIEW_INTERVALS = [0, 1, 2, 4, 7, 15, 30];

  const WORD_BANK = [
    { w: 'abandon', cn: 'v. 放弃；抛弃', ex: 'He had to abandon his car in the snow.' },
    { w: 'ability', cn: 'n. 能力；才能', ex: 'She has the ability to solve hard problems.' },
    { w: 'absolute', cn: 'adj. 绝对的；完全的', ex: 'There is no absolute truth in the world.' },
    { w: 'academic', cn: 'adj. 学术的；学院的', ex: 'He plans to pursue an academic career.' },
    { w: 'accept', cn: 'v. 接受；同意', ex: 'I accept your kind invitation.' },
    { w: 'access', cn: 'n./v. 接近；进入；使用', ex: 'Students need access to the library.' },
    { w: 'accident', cn: 'n. 意外；事故', ex: 'The accident happened at the corner.' },
    { w: 'accompany', cn: 'v. 陪伴；伴随', ex: 'She accompanied me to the station.' },
    { w: 'achieve', cn: 'v. 达到；实现', ex: 'Hard work helps you achieve your goal.' },
    { w: 'acquire', cn: 'v. 获得；习得', ex: 'Children acquire language quickly.' },
    { w: 'adapt', cn: 'v. 适应；改编', ex: 'We must adapt to the new climate.' },
    { w: 'adequate', cn: 'adj. 足够的；适当的', ex: 'The food was adequate for us.' },
    { w: 'adjust', cn: 'v. 调整；适应', ex: 'He adjusted the seat to his height.' },
    { w: 'admire', cn: 'v. 钦佩；欣赏', ex: 'I admire her courage and wisdom.' },
    { w: 'admit', cn: 'v. 承认；准许进入', ex: 'He admitted his mistake at last.' },
    { w: 'advocate', cn: 'v. 提倡；主张', ex: 'They advocate a healthy lifestyle.' },
    { w: 'afford', cn: 'v. 负担得起', ex: 'We cannot afford a long trip.' },
    { w: 'aggressive', cn: 'adj. 好斗的；进取的', ex: 'He is an aggressive salesman.' },
    { w: 'alcohol', cn: 'n. 酒精；酒', ex: 'Too much alcohol is harmful.' },
    { w: 'ambition', cn: 'n. 雄心；抱负', ex: 'Her ambition is to be a doctor.' },
    { w: 'analyze', cn: 'v. 分析', ex: 'We should analyze the data first.' },
    { w: 'ancient', cn: 'adj. 古代的；古老的', ex: 'They found an ancient coin.' },
    { w: 'anxious', cn: 'adj. 焦虑的；渴望的', ex: 'She is anxious about the exam.' },
    { w: 'apparent', cn: 'adj. 明显的；表面的', ex: 'It was apparent that he was tired.' },
    { w: 'appeal', cn: 'v./n. 呼吁；吸引', ex: 'The idea appeals to young people.' },
    { w: 'apply', cn: 'v. 申请；应用', ex: 'You should apply this rule carefully.' },
    { w: 'approach', cn: 'v./n. 接近；方法', ex: 'We need a new approach to the task.' },
    { w: 'argue', cn: 'v. 争论；主张', ex: 'They argue about the best plan.' },
    { w: 'arise', cn: 'v. 出现；升起', ex: 'A new problem arose yesterday.' },
    { w: 'aspect', cn: 'n. 方面；外观', ex: 'We studied every aspect of it.' },
    { w: 'assess', cn: 'v. 评估；评定', ex: 'Teachers assess students by tests.' },
    { w: 'assume', cn: 'v. 假定；承担', ex: 'Let us assume it is true.' },
    { w: 'attitude', cn: 'n. 态度；看法', ex: 'His attitude changed a lot.' },
    { w: 'attribute', cn: 'v. 归因于', ex: 'She attributes her success to effort.' },
    { w: 'authority', cn: 'n. 权威；当局', ex: 'The teacher is an authority on grammar.' },
    { w: 'available', cn: 'adj. 可获得的；有空的', ex: 'Is the book available online?' },
    { w: 'average', cn: 'adj./n. 平均的；平均数', ex: 'The average score rose this year.' },
    { w: 'avoid', cn: 'v. 避免；回避', ex: 'Try to avoid making the same mistake.' },
    { w: 'aware', cn: 'adj. 意识到的；知道的', ex: 'Are you aware of the risk?' },
    { w: 'benefit', cn: 'n./v. 利益；受益', ex: 'Exercise benefits your health.' },
    { w: 'beyond', cn: 'prep. 超过；在……之外', ex: 'The problem is beyond my skill.' },
    { w: 'brief', cn: 'adj. 简短的', ex: 'Please give a brief answer.' },
    { w: 'capital', cn: 'n. 首都；资本', ex: 'London is the capital of Britain.' },
    { w: 'career', cn: 'n. 职业；生涯', ex: 'She has a career in medicine.' },
    { w: 'challenge', cn: 'n./v. 挑战', ex: 'He accepted the challenge bravely.' },
    { w: 'character', cn: 'n. 性格；角色', ex: 'Honesty is part of his character.' },
    { w: 'circumstance', cn: 'n. 情况；环境', ex: 'Under no circumstance should we lie.' },
    { w: 'comment', cn: 'n./v. 评论', ex: 'She refused to comment on it.' },
    { w: 'commit', cn: 'v. 犯；承诺', ex: 'He committed himself to the work.' },
    { w: 'community', cn: 'n. 社区；群体', ex: 'The community built a new park.' },
    { w: 'compare', cn: 'v. 比较', ex: 'Compare the two answers carefully.' },
    { w: 'compete', cn: 'v. 竞争；比赛', ex: 'They compete for the prize.' },
    { w: 'complex', cn: 'adj. 复杂的', ex: 'The machine is rather complex.' },
    { w: 'conclude', cn: 'v. 结论；结束', ex: 'We concluded the meeting at noon.' },
    { w: 'conduct', cn: 'v. 进行；引导', ex: 'She will conduct the experiment.' },
    { w: 'confident', cn: 'adj. 自信的', ex: 'He is confident of success.' },
    { w: 'conflict', cn: 'n./v. 冲突', ex: 'A conflict arose between them.' },
    { w: 'confuse', cn: 'v. 使困惑', ex: 'Do not confuse these two words.' },
    { w: 'conscious', cn: 'adj. 有意识的', ex: 'He was conscious during the talk.' },
    { w: 'consequence', cn: 'n. 结果；后果', ex: 'Face the consequence of your act.' },
    { w: 'considerable', cn: 'adj. 相当大的', ex: 'It took considerable time.' },
    { w: 'consist', cn: 'v. 组成', ex: 'The team consists of ten people.' },
    { w: 'constant', cn: 'adj. 持续的；恒定的', ex: 'The noise is a constant bother.' },
    { w: 'consume', cn: 'v. 消耗；消费', ex: 'Cars consume a lot of fuel.' },
    { w: 'contact', cn: 'n./v. 接触；联系', ex: 'Keep in contact with old friends.' },
    { w: 'contemporary', cn: 'adj. 当代的', ex: 'He studies contemporary art.' },
    { w: 'contrast', cn: 'n./v. 对比', ex: 'The contrast is quite clear.' },
    { w: 'contribute', cn: 'v. 贡献；投稿', ex: 'He contributed to the project.' },
    { w: 'controversial', cn: 'adj. 有争议的', ex: 'It is a controversial topic.' },
    { w: 'convince', cn: 'v. 使信服', ex: 'She convinced me to join.' },
    { w: 'correspond', cn: 'v. 通信；符合', ex: 'His words correspond to facts.' },
    { w: 'crucial', cn: 'adj. 关键的', ex: 'Timing is crucial to success.' },
    { w: 'culture', cn: 'n. 文化', ex: 'Food reflects local culture.' },
    { w: 'curious', cn: 'adj. 好奇的', ex: 'The child is curious about stars.' },
    { w: 'deceive', cn: 'v. 欺骗', ex: 'Do not deceive your friends.' },
    { w: 'decline', cn: 'v./n. 下降；拒绝', ex: 'Sales began to decline.' },
    { w: 'decorate', cn: 'v. 装饰', ex: 'They decorate the room for fest.' },
    { w: 'delicate', cn: 'adj. 精致的；脆弱的', ex: 'The glass is delicate.' },
    { w: 'demand', cn: 'n./v. 要求；需求', ex: 'The job demands patience.' },
    { w: 'depression', cn: 'n. 沮丧；萧条', ex: 'He fell into depression.' },
    { w: 'derive', cn: 'v. 源自；获得', ex: 'We derive heat from the sun.' },
    { w: 'deserve', cn: 'v. 应得', ex: 'He deserves the prize.' },
    { w: 'device', cn: 'n. 装置；设备', ex: 'This is a useful device.' },
    { w: 'diminish', cn: 'v. 减少；削弱', ex: 'His strength diminished.' },
    { w: 'distinct', cn: 'adj. 明显的；独特的', ex: 'They have distinct accents.' },
    { w: 'distribute', cn: 'v. 分配；分发', ex: 'They distribute food to the poor.' },
    { w: 'diverse', cn: 'adj. 多样的', ex: 'The city has a diverse culture.' },
    { w: 'dominate', cn: 'v. 支配；主导', ex: 'One team dominated the game.' },
    { w: 'economy', cn: 'n. 经济', ex: 'The economy is growing.' },
    { w: 'efficient', cn: 'adj. 高效的', ex: 'She is an efficient worker.' },
    { w: 'elaborate', cn: 'adj./v. 精心制作的；详述', ex: 'He gave an elaborate plan.' },
    { w: 'element', cn: 'n. 元素；要素', ex: 'Water is an element of life.' },
    { w: 'embrace', cn: 'v. 拥抱；接受', ex: 'We should embrace change.' },
    { w: 'emerge', cn: 'v. 出现；浮现', ex: 'A new star emerged.' },
    { w: 'emphasize', cn: 'v. 强调', ex: 'He emphasized the key point.' },
    { w: 'enhance', cn: 'v. 提高；增强', ex: 'Music can enhance mood.' },
    { w: 'enormous', cn: 'adj. 巨大的', ex: 'They made an enormous profit.' },
    { w: 'ensure', cn: 'v. 确保', ex: 'Please ensure your safety.' },
    { w: 'entire', cn: 'adj. 整个的', ex: 'The entire wall was painted.' },
    { w: 'environment', cn: 'n. 环境', ex: 'We must protect the environment.' },
    { w: 'essential', cn: 'adj. 必要的', ex: 'Water is essential to life.' },
    { w: 'establish', cn: 'v. 建立', ex: 'They established a new school.' },
    { w: 'evaluate', cn: 'v. 评价；评估', ex: 'We evaluate the result.' },
    { w: 'evident', cn: 'adj. 明显的', ex: 'It is evident he lied.' },
    { w: 'evolve', cn: 'v. 进化；发展', ex: 'Language evolves over time.' },
    { w: 'exaggerate', cn: 'v. 夸大', ex: 'Do not exaggerate the risk.' },
    { w: 'exhaust', cn: 'v. 耗尽；使精疲力竭', ex: 'The long trip exhausted us.' },
    { w: 'existence', cn: 'n. 存在', ex: 'The existence of life on Mars?' },
    { w: 'expand', cn: 'v. 扩张；扩展', ex: 'The business expanded fast.' },
    { w: 'expense', cn: 'n. 花费；开支', ex: 'Cut down on daily expense.' },
    { w: 'explicit', cn: 'adj. 明确的', ex: 'He gave explicit instructions.' },
    { w: 'explore', cn: 'v. 探索', ex: 'They explore the deep forest.' },
    { w: 'expose', cn: 'v. 暴露；使接触', ex: 'Do not expose it to the sun.' },
    { w: 'extend', cn: 'v. 延伸；延长', ex: 'We extended the deadline.' },
    { w: 'external', cn: 'adj. 外部的', ex: 'The external wall needs paint.' },
    { w: 'fascinate', cn: 'v. 使着迷', ex: 'The story fascinated the kids.' },
    { w: 'fatal', cn: 'adj. 致命的', ex: 'A fatal error ended the run.' },
    { w: 'feature', cn: 'n./v. 特征；以…为特色', ex: 'The app features a clean UI.' },
    { w: 'fierce', cn: 'adj. 激烈的；凶猛的', ex: 'They had a fierce debate.' },
    { w: 'finance', cn: 'n. 金融；财政', ex: 'She works in finance.' },
    { w: 'flexible', cn: 'adj. 灵活的', ex: 'We need a flexible plan.' },
    { w: 'fluent', cn: 'adj. 流利的', ex: 'She is fluent in English.' },
    { w: 'focus', cn: 'n./v. 焦点；集中', ex: 'Focus on the main task.' },
    { w: 'forbid', cn: 'v. 禁止', ex: 'Smoking is forbidden here.' },
    { w: 'former', cn: 'adj. 前者的；以前的', ex: 'The former is better.' },
    { w: 'fortunate', cn: 'adj. 幸运的', ex: 'We are fortunate to have you.' },
    { w: 'foundation', cn: 'n. 基础；基金', ex: 'Reading is the foundation of study.' },
    { w: 'fragile', cn: 'adj. 脆弱的', ex: 'The vase is fragile.' },
    { w: 'frequent', cn: 'adj. 频繁的', ex: 'He makes frequent trips.' },
    { w: 'fulfill', cn: 'v. 履行；实现', ex: 'She fulfilled her promise.' },
    { w: 'fundamental', cn: 'adj. 基本的', ex: 'Math is fundamental to science.' },
    { w: 'generate', cn: 'v. 产生；生成', ex: 'The plant generates oxygen.' },
    { w: 'genuine', cn: 'adj. 真正的；真诚的', ex: 'He showed genuine concern.' },
    { w: 'global', cn: 'adj. 全球的', ex: 'Global warming is serious.' },
    { w: 'grasp', cn: 'v. 抓住；理解', ex: 'He grasped the idea quickly.' },
    { w: 'guarantee', cn: 'v./n. 保证', ex: 'We guarantee quality.' },
    { w: 'harmony', cn: 'n. 和谐', ex: 'Live in harmony with nature.' },
    { w: 'hesitate', cn: 'v. 犹豫', ex: 'Do not hesitate to ask.' },
    { w: 'highlight', cn: 'v. 突出；强调', ex: 'The report highlights the risk.' },
    { w: 'horizon', cn: 'n. 地平线；视野', ex: 'A ship appeared on the horizon.' },
    { w: 'humble', cn: 'adj. 谦逊的；卑微的', ex: 'Stay humble and keep learning.' },
    { w: 'identity', cn: 'n. 身份；认同', ex: 'Please show your identity.' },
    { w: 'ignore', cn: 'v. 忽视', ex: 'Do not ignore the warning.' },
    { w: 'illustrate', cn: 'v. 说明；图解', ex: 'The chart illustrates the trend.' },
    { w: 'immense', cn: 'adj. 巨大的', ex: 'The ocean is immense.' },
    { w: 'impact', cn: 'n./v. 影响；冲击', ex: 'The book had a big impact.' },
    { w: 'implement', cn: 'v. 实施', ex: 'We will implement the plan.' },
    { w: 'implicit', cn: 'adj. 含蓄的', ex: 'He gave an implicit answer.' },
    { w: 'imply', cn: 'v. 暗示', ex: 'His words imply agreement.' },
    { w: 'incident', cn: 'n. 事件', ex: 'A strange incident occurred.' },
    { w: 'incline', cn: 'v. 倾向于', ex: 'I incline to agree.' },
    { w: 'increase', cn: 'v./n. 增加', ex: 'Sales increase each month.' },
    { w: 'indicate', cn: 'v. 表明；指示', ex: 'The light indicates danger.' },
    { w: 'inevitable', cn: 'adj. 不可避免的', ex: 'Change is inevitable.' },
    { w: 'infer', cn: 'v. 推断', ex: 'We infer the cause from clues.' },
    { w: 'influence', cn: 'n./v. 影响', ex: 'Parents influence children.' },
    { w: 'inherent', cn: 'adj. 固有的', ex: 'Risk is inherent in trade.' },
    { w: 'initiate', cn: 'v. 发起；开始', ex: 'They initiated a new project.' },
    { w: 'innovate', cn: 'v. 创新', ex: 'We must innovate to survive.' },
    { w: 'instance', cn: 'n. 实例', ex: 'For instance, try this way.' },
    { w: 'institute', cn: 'n. 机构；学院', ex: 'He joined a research institute.' },
    { w: 'instruct', cn: 'v. 指示；教导', ex: 'She instructed the students.' },
    { w: 'intense', cn: 'adj. 强烈的', ex: 'The heat is intense.' },
    { w: 'interact', cn: 'v. 互动', ex: 'Teachers interact with students.' },
    { w: 'internal', cn: 'adj. 内部的', ex: 'The internal part broke.' },
    { w: 'interpret', cn: 'v. 解释；口译', ex: 'How do you interpret this?' },
    { w: 'interval', cn: 'n. 间隔', ex: 'Take a short interval.' },
    { w: 'involve', cn: 'v. 涉及；包含', ex: 'The job involves travel.' },
    { w: 'isolate', cn: 'v. 隔离', ex: 'Sick plants were isolated.' },
    { w: 'justify', cn: 'v. 证明…正当', ex: 'He tried to justify his act.' },
    { w: 'legitimate', cn: 'adj. 合法的；合理的', ex: 'It is a legitimate claim.' },
    { w: 'limited', cn: 'adj. 有限的', ex: 'Time is limited.' },
    { w: 'locate', cn: 'v. 位于；定位', ex: 'The shop is located downtown.' },
    { w: 'maintain', cn: 'v. 维持；保养', ex: 'Maintain a healthy diet.' },
    { w: 'massive', cn: 'adj. 巨大的；大量的', ex: 'A massive rock blocked the road.' },
    { w: 'mature', cn: 'adj. 成熟的', ex: 'He is mature for his age.' },
    { w: 'maximum', cn: 'adj./n. 最大的', ex: 'Set the maximum speed.' },
    { w: 'minimum', cn: 'adj./n. 最小的', ex: 'We need a minimum of two.' },
    { w: 'modify', cn: 'v. 修改', ex: 'Modify the code as needed.' },
    { w: 'monitor', cn: 'v./n. 监控；显示器', ex: 'They monitor the system.' },
    { w: 'mutual', cn: 'adj. 相互的', ex: 'They have mutual respect.' },
    { w: 'negotiate', cn: 'v. 谈判', ex: 'They negotiate a deal.' },
    { w: 'neutral', cn: 'adj. 中立的', ex: 'Stay neutral in the fight.' },
    { w: 'nevertheless', cn: 'adv. 然而；不过', ex: 'It is hard; nevertheless we try.' },
    { w: 'observe', cn: 'v. 观察；遵守', ex: 'Observe the rules, please.' },
    { w: 'obtain', cn: 'v. 获得', ex: 'He obtained a rare book.' },
    { w: 'obvious', cn: 'adj. 明显的', ex: 'The answer is obvious.' },
    { w: 'occupy', cn: 'v. 占据', ex: 'The desk occupies much space.' },
    { w: 'occur', cn: 'v. 发生；出现', ex: 'Errors occur sometimes.' },
    { w: 'offend', cn: 'v. 冒犯', ex: 'I hope I did not offend you.' },
    { w: 'omit', cn: 'v. 省略；遗漏', ex: 'Do not omit any step.' },
    { w: 'opponent', cn: 'n. 对手', ex: 'He beat his opponent.' },
    { w: 'optimistic', cn: 'adj. 乐观的', ex: 'She is optimistic about the future.' },
    { w: 'original', cn: 'adj. 原始的；原创的', ex: 'Keep the original file.' },
    { w: 'overcome', cn: 'v. 克服', ex: 'We overcame the difficulty.' },
    { w: 'parallel', cn: 'adj. 平行的', ex: 'Draw two parallel lines.' },
    { w: 'participate', cn: 'v. 参与', ex: 'All can participate.' },
    { w: 'particular', cn: 'adj. 特别的；特定的', ex: 'Pay attention to this particular point.' },
    { w: 'passion', cn: 'n. 热情', ex: 'She has a passion for music.' },
    { w: 'passive', cn: 'adj. 被动的', ex: 'He took a passive role.' },
    { w: 'patient', cn: 'adj. 耐心的', ex: 'Be patient with kids.' },
    { w: 'peak', cn: 'n. 顶峰', ex: 'We reached the peak at dawn.' },
    { w: 'perceive', cn: 'v. 察觉；理解', ex: 'He perceived the change.' },
    { w: 'perfect', cn: 'adj. 完美的', ex: 'Practice makes perfect.' },
    { w: 'perform', cn: 'v. 表演；执行', ex: 'They perform well under pressure.' },
    { w: 'permanent', cn: 'adj. 永久的', ex: 'We seek permanent peace.' },
    { w: 'persist', cn: 'v. 坚持', ex: 'Persist and you will win.' },
    { w: 'phenomenon', cn: 'n. 现象', ex: 'Rainbow is a natural phenomenon.' },
    { w: 'pollute', cn: 'v. 污染', ex: 'Factories pollute the river.' },
    { w: 'precise', cn: 'adj. 精确的', ex: 'Give a precise number.' },
    { w: 'predict', cn: 'v. 预测', ex: 'We predict a warm winter.' },
    { w: 'prefer', cn: 'v. 更喜欢', ex: 'I prefer tea to coffee.' },
    { w: 'preliminary', cn: 'adj. 初步的', ex: 'A preliminary test was done.' },
    { w: 'preserve', cn: 'v. 保护；保存', ex: 'We must preserve nature.' },
    { w: 'prevail', cn: 'v. 盛行；获胜', ex: 'Truth will prevail.' },
    { w: 'primary', cn: 'adj. 主要的；初级的', ex: 'Our primary goal is clear.' },
    { w: 'priority', cn: 'n. 优先', ex: 'Safety is the top priority.' },
    { w: 'proceed', cn: 'v. 继续；进行', ex: 'We proceed to the next step.' },
    { w: 'process', cn: 'n./v. 过程；处理', ex: 'The process takes a week.' },
    { w: 'profession', cn: 'n. 职业', ex: 'Teaching is a noble profession.' },
    { w: 'profound', cn: 'adj. 深刻的', ex: 'The book had a profound effect.' },
    { w: 'prohibit', cn: 'v. 禁止', ex: 'The law prohibits smoking.' },
    { w: 'promote', cn: 'v. 促进；提升', ex: 'Exercise promotes health.' },
    { w: 'propose', cn: 'v. 提议', ex: 'He proposed a new idea.' },
    { w: 'prospect', cn: 'n. 前景', ex: 'The prospect is bright.' },
    { w: 'prosper', cn: 'v. 繁荣', ex: 'The town began to prosper.' },
    { w: 'protect', cn: 'v. 保护', ex: 'Protect your eyes from light.' },
    { w: 'provided', cn: 'conj. 假如；只要', ex: 'We go provided it is sunny.' },
    { w: 'publish', cn: 'v. 出版；发布', ex: 'They publish a new book.' },
    { w: 'pursue', cn: 'v. 追求；从事', ex: 'Pursue your dream.' },
    { w: 'qualify', cn: 'v. 使合格', ex: 'He qualified for the job.' },
    { w: 'quality', cn: 'n. 质量；品质', ex: 'We value quality over speed.' },
    { w: 'quantity', cn: 'n. 数量', ex: 'A small quantity is enough.' },
    { w: 'radical', cn: 'adj. 根本的；激进的', ex: 'A radical change is needed.' },
    { w: 'random', cn: 'adj. 随机的', ex: 'Pick a random card.' },
    { w: 'range', cn: 'n./v. 范围；变动', ex: 'Prices range from 1 to 10.' },
    { w: 'react', cn: 'v. 反应', ex: 'How did he react?' },
    { w: 'realm', cn: 'n. 领域；王国', ex: 'In the realm of art.' },
    { w: 'recover', cn: 'v. 恢复', ex: 'He recovered from illness.' },
    { w: 'reflect', cn: 'v. 反映；反思', ex: 'The mirror reflects light.' },
    { w: 'reform', cn: 'v./n. 改革', ex: 'They reform the system.' },
    { w: 'refresh', cn: 'v. 刷新；使恢复', ex: 'Refresh the page, please.' },
    { w: 'regard', cn: 'v./n. 看待；致意', ex: 'I regard him as a friend.' },
    { w: 'region', cn: 'n. 地区', ex: 'This region is cold.' },
    { w: 'register', cn: 'v. 登记；注册', ex: 'Please register your name.' },
    { w: 'regulate', cn: 'v. 调节；管理', ex: 'Laws regulate trade.' },
    { w: 'reinforce', cn: 'v. 加强', ex: 'We reinforce the wall.' },
    { w: 'reject', cn: 'v. 拒绝', ex: 'They reject the plan.' },
    { w: 'relate', cn: 'v. 关联；叙述', ex: 'These facts relate to the case.' },
    { w: 'release', cn: 'v. 释放；发布', ex: 'They release a new song.' },
    { w: 'relevant', cn: 'adj. 相关的', ex: 'Keep the talk relevant.' },
    { w: 'reliable', cn: 'adj. 可靠的', ex: 'He is a reliable friend.' },
    { w: 'relieve', cn: 'v. 缓解；减轻', ex: 'The medicine relieves pain.' },
    { w: 'reluctant', cn: 'adj. 不情愿的', ex: 'He was reluctant to go.' },
    { w: 'remark', cn: 'n./v. 评论', ex: 'She remarked on the weather.' },
    { w: 'remind', cn: 'v. 提醒', ex: 'Remind me of the date.' },
    { w: 'remote', cn: 'adj. 遥远的', ex: 'They live in a remote village.' },
    { w: 'remove', cn: 'v. 移除', ex: 'Remove the old file.' },
    { w: 'replace', cn: 'v. 替换', ex: 'Replace the broken part.' },
    { w: 'represent', cn: 'v. 代表', ex: 'He represents our team.' },
    { w: 'reputation', cn: 'n. 声誉', ex: 'The school has a good reputation.' },
    { w: 'reserve', cn: 'v. 保留；预订', ex: 'We reserve a room.' },
    { w: 'resolve', cn: 'v. 解决；决心', ex: 'We resolve the issue.' },
    { w: 'resource', cn: 'n. 资源', ex: 'Water is a key resource.' },
    { w: 'respond', cn: 'v. 回应', ex: 'She did not respond.' },
    { w: 'restore', cn: 'v. 恢复；修复', ex: 'They restore the old temple.' },
    { w: 'restrict', cn: 'v. 限制', ex: 'Speed is restricted here.' },
    { w: 'retain', cn: 'v. 保留', ex: 'Retain this document.' },
    { w: 'reveal', cn: 'v. 揭示；透露', ex: 'The letter reveals a secret.' },
    { w: 'reverse', cn: 'v./adj. 反转；相反的', ex: 'Reverse the order, please.' },
    { w: 'reward', cn: 'n./v. 奖励', ex: 'Hard work brings reward.' },
    { w: 'routine', cn: 'n. 常规', ex: 'A daily routine helps focus.' },
    { w: 'sacrifice', cn: 'v./n. 牺牲', ex: 'He made a great sacrifice.' },
    { w: 'scarce', cn: 'adj. 稀缺的', ex: 'Water is scarce in desert.' },
    { w: 'scatter', cn: 'v. 散开；分散', ex: 'The wind scatters the leaves.' },
    { w: 'scheme', cn: 'n. 计划；方案', ex: 'They launched a new scheme.' },
    { w: 'scope', cn: 'n. 范围', ex: 'The scope is too broad.' },
    { w: 'secure', cn: 'adj./v. 安全的；确保', ex: 'We secure the network.' },
    { w: 'seek', cn: 'v. 寻求', ex: 'We seek the truth.' },
    { w: 'select', cn: 'v. 选择', ex: 'Select the best one.' },
    { w: 'senior', cn: 'adj. 资深的；年长的', ex: 'He is a senior engineer.' },
    { w: 'sensitive', cn: 'adj. 敏感的', ex: 'Skin is sensitive to sun.' },
    { w: 'sequence', cn: 'n. 顺序', ex: 'Follow the right sequence.' },
    { w: 'series', cn: 'n. 系列', ex: 'A series of tests were run.' },
    { w: 'settle', cn: 'v. 解决；定居', ex: 'They settle in the city.' },
    { w: 'severe', cn: 'adj. 严重的', ex: 'A severe storm hit.' },
    { w: 'shift', cn: 'v./n. 转移；轮班', ex: 'Shift your focus here.' },
    { w: 'significant', cn: 'adj. 重要的；显著的', ex: 'A significant change occurred.' },
    { w: 'similar', cn: 'adj. 相似的', ex: 'The two are similar.' },
    { w: 'simplify', cn: 'v. 简化', ex: 'Simplify the rule.' },
    { w: 'software', cn: 'n. 软件', ex: 'We write software.' },
    { w: 'source', cn: 'n. 来源', ex: 'Find the source of the error.' },
    { w: 'specific', cn: 'adj. 具体的', ex: 'Give a specific example.' },
    { w: 'stable', cn: 'adj. 稳定的', ex: 'The system is stable.' },
    { w: 'staff', cn: 'n. 员工', ex: 'The staff is friendly.' },
    { w: 'stimulate', cn: 'v. 刺激；激发', ex: 'Music stimulates the brain.' },
    { w: 'strategy', cn: 'n. 策略', ex: 'We need a clear strategy.' },
    { w: 'stress', cn: 'n./v. 压力；强调', ex: 'Do not stress too much.' },
    { w: 'strict', cn: 'adj. 严格的', ex: 'He is strict with rules.' },
    { w: 'structure', cn: 'n. 结构', ex: 'The structure is sound.' },
    { w: 'struggle', cn: 'v./n. 挣扎；奋斗', ex: 'They struggle for freedom.' },
    { w: 'subject', cn: 'n. 主题；科目', ex: 'Math is my favorite subject.' },
    { w: 'submit', cn: 'v. 提交', ex: 'Submit your work on time.' },
    { w: 'subsequent', cn: 'adj. 随后的', ex: 'In subsequent days it rained.' },
    { w: 'substance', cn: 'n. 物质；实质', ex: 'Water is a clear substance.' },
    { w: 'substitute', cn: 'v./n. 替代', ex: 'Use oil as a substitute.' },
    { w: 'succeed', cn: 'v. 成功', ex: 'They succeed at last.' },
    { w: 'sufficient', cn: 'adj. 充足的', ex: 'We have sufficient food.' },
    { w: 'suggest', cn: 'v. 建议；暗示', ex: 'I suggest a short break.' },
    { w: 'summary', cn: 'n. 总结', ex: 'Give a brief summary.' },
    { w: 'superior', cn: 'adj. 优越的', ex: 'This model is superior.' },
    { w: 'survive', cn: 'v. 幸存', ex: 'Few plants survive the frost.' },
    { w: 'suspect', cn: 'v. 怀疑', ex: 'I suspect a mistake.' },
    { w: 'sustain', cn: 'v. 维持；支撑', ex: 'The bridge sustains heavy load.' },
    { w: 'tackle', cn: 'v. 处理；应对', ex: 'We must tackle the issue.' },
    { w: 'talent', cn: 'n. 天赋', ex: 'She has a talent for music.' },
    { w: 'tend', cn: 'v. 倾向于', ex: 'Prices tend to rise.' },
    { w: 'tense', cn: 'adj. 紧张的', ex: 'The room fell tense.' },
    { w: 'terminate', cn: 'v. 终止', ex: 'They terminate the contract.' },
    { w: 'theme', cn: 'n. 主题', ex: 'The theme is friendship.' },
    { w: 'theory', cn: 'n. 理论', ex: 'Einstein’s theory changed physics.' },
    { w: 'thorough', cn: 'adj. 彻底的', ex: 'Do a thorough check.' },
    { w: 'threat', cn: 'n. 威胁', ex: 'Climate change is a threat.' },
    { w: 'tolerate', cn: 'v. 容忍', ex: 'We tolerate small errors.' },
    { w: 'tradition', cn: 'n. 传统', ex: 'Respect local tradition.' },
    { w: 'transform', cn: 'v. 转变', ex: 'Art can transform a life.' },
    { w: 'transit', cn: 'n. 运输；中转', ex: 'The transit system is busy.' },
    { w: 'transmit', cn: 'v. 传播；传送', ex: 'Bees transmit pollen.' },
    { w: 'transparent', cn: 'adj. 透明的', ex: 'The glass is transparent.' },
    { w: 'tremendous', cn: 'adj. 巨大的', ex: 'He made a tremendous effort.' },
    { w: 'trend', cn: 'n. 趋势', ex: 'The trend is upward.' },
    { w: 'ultimate', cn: 'adj. 最终的', ex: 'Our ultimate aim is peace.' },
    { w: 'undergo', cn: 'v. 经历', ex: 'He underwent surgery.' },
    { w: 'undertake', cn: 'v. 承担', ex: 'We undertake the task.' },
    { w: 'uniform', cn: 'n./adj. 制服；统一的', ex: 'Wear a uniform at school.' },
    { w: 'unique', cn: 'adj. 独特的', ex: 'Each person is unique.' },
    { w: 'universal', cn: 'adj. 普遍的', ex: 'Music is a universal language.' },
    { w: 'unlike', cn: 'prep. 与…不同', ex: 'Unlike you, I am calm.' },
    { w: 'update', cn: 'v. 更新', ex: 'Update the app, please.' },
    { w: 'utilize', cn: 'v. 利用', ex: 'Utilize your time well.' },
    { w: 'valid', cn: 'adj. 有效的', ex: 'The ticket is valid.' },
    { w: 'vanish', cn: 'v. 消失', ex: 'The mist vanished at noon.' },
    { w: 'variation', cn: 'n. 变化；变体', ex: 'There is some variation.' },
    { w: 'vary', cn: 'v. 变化', ex: 'Prices vary by season.' },
    { w: 'vehicle', cn: 'n. 车辆', ex: 'The vehicle broke down.' },
    { w: 'version', cn: 'n. 版本', ex: 'Try the latest version.' },
    { w: 'victim', cn: 'n. 受害者', ex: 'He was a victim of fraud.' },
    { w: 'view', cn: 'n./v. 观点；看待', ex: 'In my view, it is wrong.' },
    { w: 'violate', cn: 'v. 违反', ex: 'Do not violate the law.' },
    { w: 'virtual', cn: 'adj. 虚拟的', ex: 'We met in a virtual room.' },
    { w: 'visible', cn: 'adj. 可见的', ex: 'The star is visible tonight.' },
    { w: 'vital', cn: 'adj. 至关重要的', ex: 'Sleep is vital to health.' },
    { w: 'volume', cn: 'n. 音量；体积', ex: 'Turn up the volume.' },
    { w: 'voluntary', cn: 'adj. 自愿的', ex: 'It was a voluntary act.' },
    { w: 'vulnerable', cn: 'adj. 脆弱的；易受伤害的', ex: 'The old are vulnerable.' },
    { w: 'wander', cn: 'v. 漫步；走神', ex: 'Do not wander from the point.' },
    { w: 'wealth', cn: 'n. 财富', ex: 'Health is true wealth.' },
    { w: 'welfare', cn: 'n. 福利', ex: 'Child welfare matters.' },
    { w: 'whereas', cn: 'conj. 然而；鉴于', ex: 'He is rich, whereas I am poor.' },
    { w: 'whisper', cn: 'v./n. 低语', ex: 'She whispered a secret.' },
    { w: 'widespread', cn: 'adj. 广泛的', ex: 'The idea is widespread.' },
    { w: 'withdraw', cn: 'v. 撤回；取钱', ex: 'He withdrew his offer.' },
    { w: 'witness', cn: 'v./n. 目击；证人', ex: 'We witness a change.' },
    { w: 'worthwhile', cn: 'adj. 值得的', ex: 'It is a worthwhile trip.' }
  ];

  const EnglishData = {
    NEW_WORDS_PER_BATCH, REVIEW_INTERVALS, WORD_BANK
  };
  global.XEnglishData = EnglishData;
})(window);
